<?php
$cities = array (
    "Western Cape"  => array("desc" => "Western Cape, province, South Africa, situated in the southern extremity of the African continent. The provincial capital, Cape Town, is also the country’s legislative capital. Western Cape province was part of former Cape of Good Hope province until 1994. Coastline fronting the Atlantic and Indian oceans forms Western Cape’s western and southern boundaries, respectively. The province borders Northern Cape province to the north and Eastern Cape province to the east.", "towns" => array("Bellville", "Cape Town", "Constantia", "George", "Hopefield", "Oudtshoorn", "Paarl", "Simon’s Town", "Stellenbosch", "Swellendam", "Worcester")),
    "Northern Cape"  => array("desc" => "Northern Cape, province, western South Africa. It is bordered to the north by Namibia and Botswana; to the east by North West, Free State, and Eastern Cape provinces; to the south and southwest by Western Cape province; and to the west by the Atlantic Ocean. Northern Cape was administratively created out of northern and central Cape of Good Hope province in 1994. Kimberley is the provincial capital.", "towns" => array("Kimberley", "Kuruman", "Port Nolloth")),
    "North West"  => array("desc" => "North West, also spelled North-West, province, north-central South Africa. It was created in 1994 from portions of Transvaal and Cape of Good Hope provinces. North West is bounded by Botswana to the north and northwest, Limpopo province to the northeast, Gauteng province to the east, Free State province to the southeast, and Northern Cape province to the southwest. The provincial capital is Mafikeng.", "towns" => array("Klerksdorp", "Mahikeng", "Mmabatho", "Potchefstroom", "Rustenburg")),
    "Mpumalanga"  => array("desc" => "Mpumalanga, formerly (1994–95) Eastern Transvaal, province, northeastern South Africa. It is bounded by Limpopo province to the north, Mozambique and Swaziland to the east, the provinces of KwaZulu-Natal and Free State to the south, and Gauteng province to the west. Mpumalanga province (called Eastern Transvaal province in 1994–95) was part of former Transvaal province until 1994. Nelspruit is the provincial capital.", "towns" => array("Emalahleni", "Nelspruit", "Secunda")),
    "Limpopo"  => array("desc" => "Limpopo, formerly (1994–2002) Northern, province, northeastern South Africa. The northernmost South African province, it is bounded by Zimbabwe to the north; Mozambique to the east; the provinces of Mpumalanga, Gauteng, and North West to the south; and Botswana to the west and northwest. Limpopo (known as Northern in 1994–2002) was created out of part of Transvaal province in 1994. Polokwane is the provincial capital.", "towns" => array( "Giyani", "Lebowakgomo", "Musina", "Phalaborwa", "Polokwane", "Seshego", "Sibasa", "Thabazimbi")),
    "KwaZulu-Natal"  => array("desc" => "KwaZulu-Natal, formerly Natal, province of South Africa, occupying the southeastern portion of the country. It is bounded to the north by Swaziland and Mozambique, to the east by the Indian Ocean, to the south by Eastern Cape province, to the west by Lesotho and Free State province, and to the northwest by Mpumalanga province. Within KwaZulu-Natal is an enclave of Eastern Cape province consisting of the eastern portion of the former Griqualand East (around Umzimkulu). The provincial capital is Pietermaritzburg.", "towns" => array("Durban", "Empangeni", "Ladysmith", "Newcastle", "Pietermaritzburg", "Pinetown", "Ulundi", "Umlazi")),
    "Gauteng"  => array("desc" => "Gauteng, province, northeastern South Africa. It consists of the cities of Pretoria, Johannesburg, Germiston, and Vereeniging and their surrounding metropolitan areas in the eastern part of the Witwatersrand region. Gauteng is the smallest South African province. It is bordered by the provinces of Limpopo on the north, Mpumalanga on the east, Free State on the south, and North West on the west. Until 1994 Gauteng (called Pretoria-Witwatersrand-Vereeniging in 1994–95) was part of the former Transvaal province. The provincial capital is Johannesburg.", "towns" => array("Benoni", "Boksburg", "Brakpan", "Carletonville", "Germiston", "Johannesburg", "Krugersdorp", "Pretoria", "Randburg", "Randfontein", "Roodepoort", "Soweto", "Springs", "Vanderbijlpark", "Vereeniging")),
    "Free State"  => array("desc" => "Free State, province, east-central Republic of South Africa. Under the name Orange Free State, it was originally a Boer state and then (from 1910) one of the traditional provinces of South Africa; it was renamed Free State in 1995. Free State is bordered on the north by North West, Gauteng, and Mpumalanga provinces, on the east by KwaZulu-Natal province and the independent state of Lesotho, on the south by Eastern Cape province, and on the west by Northern Cape province. The provincial capital, Bloemfontein, is also the national judicial capital.", "towns" => array("Bethlehem", "Bloemfontein", "Jagersfontein", "Kroonstad", "Odendaalsrus", "Parys", "Phuthaditjhaba", "Sasolburg", "Virginia", "Welkom")),
    "Eastern Cape"  => array("desc" => "Eastern Cape, province, south-central South Africa. It is bordered by Western Cape province to the west, Northern Cape province to the northwest, Free State province and Lesotho to the north, KwaZulu-Natal province to the northeast, and the Indian Ocean to the southeast and south. The eastern portion of the former Griqualand East (surrounding Umzimkulu) is now an exclave of Eastern Cape located in southern KwaZulu-Natal. Eastern Cape was part of former Cape of Good Hope province until 1994. Bisho is the provincial capital.", "towns" => array("Alice", "Butterworth", "East London", "Graaff-Reinet", "Grahamstown", "King William’s Town", "Mthatha", "Port Elizabeth", "Queenstown", "Uitenhage", "Zwelitsha"))
);
